// <auto-generated />
namespace mvcday1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class PopulatedGenre : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PopulatedGenre));
        
        string IMigrationMetadata.Id
        {
            get { return "201910040443277_PopulatedGenre"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
